# Generated by Django 3.1 on 2020-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_register_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
