# Generated by Django 3.1 on 2021-02-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_register_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='tab',
            field=models.IntegerField(default=100),
        ),
    ]
