# Generated by Django 3.1 on 2021-02-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20210212_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='tab',
            field=models.IntegerField(default=4),
        ),
    ]
